# Basic Redis Configuration

# IP
bind 0.0.0.0

# Port
port 6379

# Close connection after idle time (seconds)
timeout 0

# Set server mode (no or yes)
protected-mode no

# Specify logging level
loglevel notice

# Don't save data to disk automatically
save ""

# Set max memory and eviction policy
maxmemory 512mb
maxmemory-policy allkeys-lru

# Enable AOF (Append Only File) persistence
appendonly no

# Max clients (connections) allowed
maxclients 10000 
